### ISSUE TITLE
Crashes if it cannot immediately connect

### ISSUE THREAD

**Issue by zi0r** [optix2000/nsd_exporter#1]
Better behavior would be to sleep and retry the connection instead of this:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ee6c6]

goroutine 1 [running]:
io/ioutil.devNull.ReadFrom(0x0, 0x0, 0x0, 0x7ea2c0, 0x800b73601, 0x800c1aa38)
        /usr/local/go/src/io/ioutil/ioutil.go:147 +0x66
io.copyBuffer(0x8bcaa0, 0xb86f08, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7c0a60, 0x201, 0xc0003aae40)
        /usr/local/go/src/io/io.go:388 +0x303
io.Copy(0x8bcaa0, 0xb86f08, 0x0, 0x0, 0x0, 0x8bc060, 0xc00042a6e0)
        /usr/local/go/src/io/io.go:364 +0x5a
github.com/optix2000/go-nsdctl.NewClient(0x84f3c5, 0x3, 0x7fffffffedc5, 0xe, 0x7fffffffed6e, 0x21, 0x7fffffffed95, 0x22, 0x7fffffffed47, 0x22, ...)
        /wrkdirs/usr/ports/net-mgmt/nsd_exporter/work/src/github.com/optix2000/go-nsdctl/nsdctl.go:267 +0x58d
main.NewNSDCollector(0x84f3c5, 0x3, 0x7fffffffedc5, 0xe, 0x7fffffffed6e, 0x21, 0x7fffffffed95, 0x22, 0x7fffffffed47, 0x22, ...)
        /wrkdirs/usr/ports/net-mgmt/nsd_exporter/work/src/github.com/optix2000/nsd_exporter/nsd_exporter.go:150 +0xc1
main.main()
        /wrkdirs/usr/ports/net-mgmt/nsd_exporter/work/src/github.com/optix2000/nsd_exporter/nsd_exporter.go:201 +0x30f

**Comment by optix2000** [comment]
Fixed in https://github.com/optix2000/go-nsdctl/commit/ce14b3286e5126cf7e3d999eaedc7757e62b8a2c

However exiting on error during startup is actually intentional, mainly to catch obvious misconfigurations that would otherwise need to wait for a scrape to manifest.

**Comment by zi0r** [comment]
Thanks!
