### ISSUE TITLE
Not parsing command line arguments correctly

### ISSUE THREAD

**Issue by rootwyrm** [optix2000/nsd_exporter#6]
Seeing this after building on Alpine 3.12 with Go 1.13 from aports;

```
# ./nsd_exporter -config-file /usr/local/etc/nsd/nsd.conf
2020/07/14 15:30:30 open /usr/local/etc/nsd/nsd: no such file or directory
# ./nsd_exporter -key /usr/local/etc/nsd/nsd_control.key -cert /usr/local/etc/nsd/nsd_control.pem -ca /usr/local/etc/nsd/nsd_server.pem
2020/07/14 15:28:33 -cert, -key, and -ca must all be defined.
```

**Comment by hmrodrigues** [comment]
I'm also having this issue

Built on OpenBSD with Go 1.13.9

**Comment by hmrodrigues** [comment]
I was able to start by also adding -nsd-address to -ca, -key and -cert

/opt/nsd_exporter/nsd_exporter -cert /var/nsd/etc/nsd_control.pem -key /var/nsd/etc/nsd_control.key -ca /var/nsd/etc/nsd_server.pem -nsd-address 127.0.0.1:8952

**Comment by optix2000** [comment]
By default, `nsd_exporter` tries to read config data from `/etc/nsd/nsd.conf`. This means that for setups that don't install the config to `/etc/nsd` (ie `/usr/local/etc/nsd` or BSD filesystem layouts), you'll need to tell it where to find the config. 

You can tell it to read the alternative config (so you don't need to input everything manually by adding `-config-file /usr/local/etc/nsd/nsd.conf`

I'll fix up the text to add that you need to specific nsd-address too.
